### ISSUE TITLE
 Unresolved reference: TransactionType

### ISSUE THREAD

**Issue by gopal-fp** [DAYUCS/cordapp-bill-of-lading#1]
Unresolved reference: TransactionType
We cant find "TranscationType" class in  net.corda.core.contracts package with your sample, we have tried with corda-core 2.0.0 and 1.0.0 
Any help will be much appreciated.

**Comment by DAYUCS** [comment]
net.corda.core.contracts.TransactionType only exists before Corda V1.0.0, e.g. M14. 

Would you please pull the latest version of my project and retry again?
